# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(max_length=30)),
                ('scan_id', models.CharField(max_length=30)),
                ('scan_type', models.CharField(max_length=30)),
            ],
        ),
    ]
