# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='accesslog',
        ),
    ]
