# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180416_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.DateField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=30)),
                ('scan_id', models.CharField(max_length=30)),
                ('access', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
