# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180417_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='action',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
    ]
