# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-27 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180827_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='entrydate',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 17, 7, 8, 43443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='entrydate',
            field=models.DateField(default=datetime.datetime(2018, 8, 27, 17, 7, 8, 42443, tzinfo=utc)),
        ),
    ]
