# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-27 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180827_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='entrydate',
            field=models.DateTimeField(default='django.utils.timezone.now()'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='entrydate',
            field=models.DateField(default='django.utils.timezone.now()'),
        ),
    ]
